import * as path from "node:path";

import type { ScanResult } from "./types.js";

/**
 * Options for code generation.
 */
export interface GeneratorOptions {
  /** Absolute path to the routes directory */
  readonly routesDir: string;
  /** Absolute path to the output file */
  readonly outputPath: string;
}

/**
 * Generate the routes file content from scanned routes and layouts.
 *
 * @param scanResult - Scanned routes and layouts
 * @param options - Generator options
 * @returns Generated TypeScript code
 */
export const generateRoutes = (
  scanResult: ScanResult,
  options: GeneratorOptions,
): string => {
  const { routes, layouts } = scanResult;
  const { routesDir, outputPath } = options;

  // Calculate relative path from output to routes
  const outputDir = path.dirname(outputPath);
  const relativeRoutesDir = path.relative(outputDir, routesDir);

  const lines: string[] = [
    "// This file is auto-generated by @effex/vite-plugin",
    "// Do not edit manually",
    "",
    'import { Route } from "@effex/platform";',
    "",
  ];

  // Generate layout imports
  if (layouts.length > 0) {
    lines.push("// Layout module imports (named exports)");
    for (const layout of layouts) {
      const importPath = path
        .join(relativeRoutesDir, layout.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import * as ${layout.importName} from "${importPath}";`);
    }

    lines.push("");
    lines.push("// Layout component imports (default exports)");
    for (const layout of layouts) {
      const importPath = path
        .join(relativeRoutesDir, layout.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import ${layout.componentImportName} from "${importPath}";`);
    }
    lines.push("");
  }

  // Generate route imports
  if (routes.length > 0) {
    lines.push("// Route module imports (named exports)");
    for (const route of routes) {
      const importPath = path
        .join(relativeRoutesDir, route.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import * as ${route.importName} from "${importPath}";`);
    }

    lines.push("");
    lines.push("// Component imports (default exports)");
    for (const route of routes) {
      const importPath = path
        .join(relativeRoutesDir, route.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import ${route.componentImportName} from "${importPath}";`);
    }
  }

  // Generate layouts object
  if (layouts.length > 0) {
    lines.push("");
    lines.push("// Layout definitions");
    lines.push("export const layouts = {");

    for (const layout of layouts) {
      if (layout.exports.hasRoute) {
        // Layout has a Route.define - use its config
        const layoutOptions: string[] = [];
        layoutOptions.push(
          `    params: ${layout.importName}.route._config.paramsSchema`,
        );
        layoutOptions.push(
          `    loader: ${layout.importName}.route._config.loader`,
        );

        lines.push(
          `  ${layout.layoutName}: Route.make(${layout.importName}.route._path, {`,
        );
        lines.push(layoutOptions.join(",\n") + ",");
        lines.push("  }),");
      } else {
        // No Route.define - create a basic layout route
        lines.push(
          `  ${layout.layoutName}: Route.make("${layout.pathPrefix}"),`,
        );
      }
    }

    lines.push("} as const;");
  }

  lines.push("");
  lines.push("// Route definitions");
  lines.push("export const routes = {");

  for (const route of routes) {
    if (route.exports.hasRoute) {
      // Use DefinedRoute - extract config and create route from it
      // The __path is injected by the vite-plugin transform
      const routeOptions: string[] = [];
      routeOptions.push(
        `    params: ${route.importName}.route._config.paramsSchema`,
      );
      routeOptions.push(`    loader: ${route.importName}.route._config.loader`);
      routeOptions.push(`    action: ${route.importName}.route._config.action`);

      lines.push(
        `  ${route.routeName}: Route.make(${route.importName}.route._path, {`,
      );
      lines.push(routeOptions.join(",\n") + ",");
      lines.push("  }),");
    } else {
      // No Route.define - create a basic route with just the path
      lines.push(`  ${route.routeName}: Route.make("${route.routePath}"),`);
    }
  }

  lines.push("} as const;");
  lines.push("");

  // Generate layout components map
  if (layouts.length > 0) {
    lines.push("// Layout component map for rendering");
    lines.push("export const layoutComponents = {");

    for (const layout of layouts) {
      lines.push(`  ${layout.layoutName}: ${layout.componentImportName},`);
    }

    lines.push("} as const;");
    lines.push("");
  }

  // Generate components map
  lines.push("// Component map for rendering routes");
  lines.push("export const components = {");

  for (const route of routes) {
    lines.push(`  ${route.routeName}: ${route.componentImportName},`);
  }

  lines.push("} as const;");
  lines.push("");

  // Generate layout hierarchy - maps route names to their layout chain
  if (layouts.length > 0) {
    lines.push("// Layout hierarchy for each route");
    lines.push("export const routeLayouts = {");

    for (const route of routes) {
      if (route.layouts.length > 0) {
        lines.push(
          `  ${route.routeName}: [${route.layouts.map((l) => `"${l}"`).join(", ")}] as const,`,
        );
      } else {
        lines.push(`  ${route.routeName}: [] as const,`);
      }
    }

    lines.push("} as const;");
    lines.push("");

    // Generate layout parent relationships
    lines.push("// Layout parent relationships");
    lines.push("export const layoutParents = {");

    for (const layout of layouts) {
      if (layout.parentLayout) {
        lines.push(
          `  ${layout.layoutName}: "${layout.parentLayout}" as const,`,
        );
      } else {
        lines.push(`  ${layout.layoutName}: null,`);
      }
    }

    lines.push("} as const;");
    lines.push("");
  }

  // Generate type exports
  lines.push("// Type inference helpers");
  lines.push("export type Routes = typeof routes;");
  lines.push("export type RouteNames = keyof Routes;");
  if (layouts.length > 0) {
    lines.push("export type Layouts = typeof layouts;");
    lines.push("export type LayoutNames = keyof Layouts;");
  }
  lines.push(
    'export type AppRouter = import("@effex/platform").RouterInfer<Routes>;',
  );
  lines.push("");

  return lines.join("\n");
};
