import * as path from "node:path";

import type { ScannedRoute } from "./types.js";

/**
 * Options for code generation.
 */
export interface GeneratorOptions {
  /** Absolute path to the routes directory */
  readonly routesDir: string;
  /** Absolute path to the output file */
  readonly outputPath: string;
}

/**
 * Generate the routes file content from scanned routes.
 *
 * @param routes - Array of scanned routes
 * @param options - Generator options
 * @returns Generated TypeScript code
 */
export const generateRoutes = (
  routes: ScannedRoute[],
  options: GeneratorOptions,
): string => {
  const { routesDir, outputPath } = options;

  // Calculate relative path from output to routes
  const outputDir = path.dirname(outputPath);
  const relativeRoutesDir = path.relative(outputDir, routesDir);

  const lines: string[] = [
    "// This file is auto-generated by @effex/vite-plugin",
    "// Do not edit manually",
    "",
    'import { Route } from "@effex/platform";',
    "",
  ];

  // Generate imports
  if (routes.length > 0) {
    lines.push("// Route module imports (named exports)");
    for (const route of routes) {
      const importPath = path
        .join(relativeRoutesDir, route.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import * as ${route.importName} from "${importPath}";`);
    }

    lines.push("");
    lines.push("// Component imports (default exports)");
    for (const route of routes) {
      const importPath = path
        .join(relativeRoutesDir, route.filePath)
        .replace(/\.(tsx?|jsx?)$/, "");
      lines.push(`import ${route.componentImportName} from "${importPath}";`);
    }
  }

  lines.push("");
  lines.push("// Route definitions");
  lines.push("export const routes = {");

  for (const route of routes) {
    if (route.exports.hasRoute) {
      // Use DefinedRoute - extract config and create route from it
      // The __path is injected by the vite-plugin transform
      const routeOptions: string[] = [];
      routeOptions.push(
        `    params: ${route.importName}.route._config.paramsSchema`,
      );
      routeOptions.push(`    loader: ${route.importName}.route._config.loader`);
      routeOptions.push(`    action: ${route.importName}.route._config.action`);

      lines.push(
        `  ${route.routeName}: Route.make(${route.importName}.route._path, {`,
      );
      lines.push(routeOptions.join(",\n") + ",");
      lines.push("  }),");
    } else {
      // No Route.define - create a basic route with just the path
      lines.push(`  ${route.routeName}: Route.make("${route.routePath}"),`);
    }
  }

  lines.push("} as const;");
  lines.push("");

  // Generate components map
  lines.push("// Component map for rendering routes");
  lines.push("export const components = {");

  for (const route of routes) {
    lines.push(`  ${route.routeName}: ${route.componentImportName},`);
  }

  lines.push("} as const;");
  lines.push("");

  // Generate type exports
  lines.push("// Type inference helpers");
  lines.push("export type Routes = typeof routes;");
  lines.push("export type RouteNames = keyof Routes;");
  lines.push(
    'export type AppRouter = import("@effex/platform").RouterInfer<Routes>;',
  );
  lines.push("");

  return lines.join("\n");
};
